language: python
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=4
    - python: 2.7
      env: PLONE_VERSION=5
    - python: 3.7
      env: PLONE_VERSION=5
install:
  - mkdir -p buildout-cache/downloads
  - pip install -r requirements.txt
  - bin/buildout -c test-$PLONE_VERSION.x.cfg
script:
  - bin/test
